### ISSUE TITLE
Google Login not working

### ISSUE THREAD

**Issue by alexy000** [stanfortonski/Tinder-Bot#1]
Hello,

EDIT: using the latest version from github, but same issue for 1.5

thanks for you programm! Sadly, for me the google login is not working. Not in the programm and not in the test. Maybe they changed something? The Broswer is opening and enters the username, but i get an error for the password (in german):

"""
Anmeldung nicht möglich
Dieser Browser oder diese App ist unter Umständen nicht sicher. Weitere Informationen
Verwenden Sie einen anderen Browser. Wenn Sie bereits einen unterstützten Browser nutzen, können Sie Ihren Bildschirm aktualisieren und noch einmal versuchen, sich anzumelden.
"""

It tells me that the Browser isnt safe.

kind regards,

Alex

Testing started at 19:36 ...
C:\Users\alexy\AppData\Local\Programs\Python\Python39\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pycharm\_jb_unittest_runner.py" --path C:/Users/alexy/PycharmProjects/Tinder-Bot/tests/googlelogin_test.py
Launching unittests with arguments python -m unittest C:/Users/alexy/PycharmProjects/Tinder-Bot/tests/googlelogin_test.py in C:\Users\alexy\PycharmProjects\Tinder-Bot\tests

=== Google Login ===

Error
Traceback (most recent call last):
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\tests\googlelogin_test.py", line 23, in testLogin
    self.gl.logIn()
  File "..\tinder\login\googlelogin.py", line 24, in logIn
    driver.find_element_by_css_selector('#password > div:first-child > div > div:first-child > input').send_keys(self.password)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #password > div:first-child > div > div:first-child > input

Assertion failed

Ran 1 test in 9.755s

FAILED (errors=1)

Process finished with exit code 1

Assertion failed

Assertion failed

**Comment by stanfortonski** [comment]
Hi, I will check your problem in free time, so weekend. Probably Tinder changed something.

Regards,
Stan Fortoński

**Comment by stanfortonski** [comment]
Yes, Google is blocking Selenium sometimes. Try Facebook if that give you the same results I will check that as I say above.

**Comment by stanfortonski** [comment]
I was tested that. Google is blocking selenium. I don't know how to solve the problem programmatically. Maybe download new geckodriver will help. I close this issue.
