### ISSUE TITLE
Like | Dislike Button: Could not be scrolled into view error

### ISSUE THREAD

**Issue by joshua-classen** [stanfortonski/Tinder-Bot#13]
By executing i will get the following error after some time:

`Traceback (most recent call last):
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/app.py", line 28, in <module>
    bot.perform()
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/tinder/tinderbot.py", line 28, in perform
    self.dislike()
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/tinder/tinderbot.py", line 62, in dislike
    self.driver.find_element_by_xpath(button).click()
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/vm/Documents/TinderBot1.7/Tinder-Bot/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <button class="bullet D(ib) Va(m) Cnt($blank)::a D(b)::a Cur(p) bullet--active H(4px)::a W(100%)::a Py(4px) Px(2px) W(100%) Bdrs(100px)::a Bgc(#fff)::a focus-background-style"> could not be scrolled into view`

This happens for example in line 61 `self.driver.find_element_by_xpath(button).click()`
**My untested rough solution: we first have to wait for the element until its clickabale.**

**Comment by joshua-classen** [comment]
Is there any way of formating Console logs properly here?

**Comment by stanfortonski** [comment]
Good proposition, there is animation between show next card. I don't really know maybe some package can style exceptions info.

**Comment by stanfortonski** [comment]
Release 1.7.1 solved: Could not be scrolled into view.
