### ISSUE TITLE
Bot gets stuck

### ISSUE THREAD

**Issue by alexy000** [stanfortonski/Tinder-Bot#2]
Hello,

EDIT: using release 1.5

Thanks for your code, perfect for corona times! It got the facebook login working, but i run into another error.

the browser stops at this page.

![tinderbot_issue](https://user-images.githubusercontent.com/48931953/99435818-f7e30d00-2910-11eb-99a0-5e2f9afb38a2.PNG)

Kind regards,

Alex

C:\Users\alexy\AppData\Local\Programs\Python\Python39\python.exe C:/Users/alexy/PycharmProjects/Tinder-Bot/executable.py
=== TinderBot Start ===
=== Facebook Login ===
=== Tinder login ===
Traceback (most recent call last):
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\executable.py", line 23, in <module>
    login.logIn()
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\tinder\login\tinderlogin.py", line 37, in logIn
    self.__closePopups()
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\tinder\login\tinderlogin.py", line 77, in __closePopups
    driver.find_element_by_xpath('/html/body/div[2]/div/div/div/div/div[3]/button[1]').click()
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <button class="button Lts($ls-s) Z(0) CenterAlign Mx(a) Cur(d) Pe(n) Op(.8) Tt(u) Ell Bdrs(100px) Px(24px) Px(20px)--s Py(0) Mih(40px) Pos(r) Ov(h) C(#fff) Bg($c-pink):h::b Bg($c-pink):f::b Bg($c-pink):a::b Trsdu($fast) Trsp($background) Bg($c-light-bluegray) Bxsh(n) Fw($semibold) focus-button-style W(225px) W(a)" type="button"> could not be scrolled into view

Process finished with exit code 1

**Comment by stanfortonski** [comment]
Hi, I will check your problem in free time, so weekend. Probably Tinder changed something.

Regards,
Stan Fortoński

**Comment by stanfortonski** [comment]
I don't detect that problem. Bot is crushing sometimes at start. You have to run again bot.
