### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by alexy000** [stanfortonski/Tinder-Bot#3]
Hello,

also the facebook login doesnt work in the latest version from github :( Browser gets stuck here

![tinderbot_issue2](https://user-images.githubusercontent.com/48931953/99437544-e864c380-2912-11eb-80bd-cfb06fdc7697.PNG)

C:\Users\alexy\AppData\Local\Programs\Python\Python39\python.exe C:/Users/alexy/PycharmProjects/Tinder-Bot/executable.py
=== TinderBot Start ===
=== Facebook Login ===
Traceback (most recent call last):
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\executable.py", line 23, in <module>
    login.logIn()
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\tinder\login\tinderlogin.py", line 25, in logIn
    self.methodLogin.logIn()
  File "C:\Users\alexy\PycharmProjects\Tinder-Bot\tinder\login\facebooklogin.py", line 22, in logIn
    driver.find_element_by_xpath('//*[@id="u_0_d"]').submit()
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alexy\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@id="u_0_d"]

Process finished with exit code 1

**Comment by stanfortonski** [comment]
Hi, I will check your problem in free time, so weekend. Probably Tinder changed something.

Regards,
Stan Fortoński

**Comment by stanfortonski** [comment]
Hi! I solve your problem. You have to download last commit :)

**Comment by stanfortonski** [comment]
I created new release Version 1.6. Try it.
